"""Generate supabase/migrations/020_reading_comprehension_catalog.sql from assets/reading JSON."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
READING_ROOT = ROOT / "app" / "src" / "main" / "assets" / "reading"
OUT = ROOT / "supabase" / "migrations" / "020_reading_comprehension_catalog.sql"
UPDATED_AT = 2026072901
DEFAULT_REWARD = 2

# Note: after the initial seed was applied, assets/reading was removed.
# Re-run only if you restore a staging JSON tree at READING_ROOT.


def dollar_quote(text: str, tag: str = "seedie") -> str:
    """Wrap text in a PostgreSQL dollar quote, picking a tag that does not appear in text."""
    base = tag
    n = 0
    while True:
        t = base if n == 0 else f"{base}{n}"
        marker = f"${t}$"
        if marker not in text:
            return f"{marker}{text}{marker}"
        n += 1


def sql_str(text: str | None) -> str:
    if text is None:
        return "NULL"
    return dollar_quote(text)


def load_sets() -> list[dict]:
    catalog = json.loads((READING_ROOT / "catalog.json").read_text(encoding="utf-8"))
    sets: list[dict] = []
    for index, entry in enumerate(catalog["sets"]):
        path = READING_ROOT / entry["file"]
        data = json.loads(path.read_text(encoding="utf-8"))
        data["_sort_order"] = index
        sets.append(data)
    return sets


def build_ddl() -> str:
    return """-- Reading comprehension catalog (grade-8 starter bank)
-- Generated by scripts/generate_reading_seed.py — do not hand-edit seed rows.

CREATE TABLE IF NOT EXISTS public.reading_sets (
    set_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    title_zh TEXT,
    grade INT NOT NULL DEFAULT 8,
    difficulty TEXT NOT NULL DEFAULT 'medium',
    topic TEXT,
    passage TEXT NOT NULL,
    word_count INT NOT NULL DEFAULT 0,
    estimated_minutes INT NOT NULL DEFAULT 8,
    sort_order INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.reading_questions (
    question_id TEXT PRIMARY KEY,
    set_id TEXT NOT NULL REFERENCES public.reading_sets(set_id) ON DELETE CASCADE,
    question_type TEXT,
    stem TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    correct_option_id TEXT NOT NULL,
    explanation TEXT NOT NULL,
    highlight_word TEXT,
    reward_token INT NOT NULL DEFAULT 2
);

CREATE TABLE IF NOT EXISTS public.reading_options (
    question_id TEXT NOT NULL REFERENCES public.reading_questions(question_id) ON DELETE CASCADE,
    option_id TEXT NOT NULL,
    option_text TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (question_id, option_id)
);

CREATE INDEX IF NOT EXISTS reading_sets_sort_order_idx
    ON public.reading_sets (sort_order);

CREATE INDEX IF NOT EXISTS reading_questions_set_sort_idx
    ON public.reading_questions (set_id, sort_order);

ALTER TABLE public.reading_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_options ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view reading sets" ON public.reading_sets;
CREATE POLICY "Anyone can view reading sets"
    ON public.reading_sets FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view reading questions" ON public.reading_questions;
CREATE POLICY "Anyone can view reading questions"
    ON public.reading_questions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view reading options" ON public.reading_options;
CREATE POLICY "Anyone can view reading options"
    ON public.reading_options FOR SELECT USING (true);

GRANT SELECT ON public.reading_sets TO anon, authenticated;
GRANT SELECT ON public.reading_questions TO anon, authenticated;
GRANT SELECT ON public.reading_options TO anon, authenticated;
"""


def build_seed(sets: list[dict]) -> str:
    lines: list[str] = ["-- Seed grade-8 reading bank"]

    set_ids = [s["id"] for s in sets]
    id_list = ", ".join(f"'{sid}'" for sid in set_ids)

    for s in sets:
        lines.append(
            f"""
INSERT INTO public.reading_sets (
    set_id, title, title_zh, grade, difficulty, topic, passage,
    word_count, estimated_minutes, sort_order, version, updated_at
) VALUES (
    '{s["id"]}',
    {sql_str(s["title"])},
    {sql_str(s.get("titleZh"))},
    {int(s.get("grade", 8))},
    {sql_str(s.get("difficulty", "medium"))},
    {sql_str(s.get("topic"))},
    {sql_str(s["passage"])},
    {int(s.get("wordCount", 0))},
    {int(s.get("estimatedMinutes", 8))},
    {int(s["_sort_order"])},
    1,
    {UPDATED_AT}
)
ON CONFLICT (set_id) DO UPDATE SET
    title = EXCLUDED.title,
    title_zh = EXCLUDED.title_zh,
    grade = EXCLUDED.grade,
    difficulty = EXCLUDED.difficulty,
    topic = EXCLUDED.topic,
    passage = EXCLUDED.passage,
    word_count = EXCLUDED.word_count,
    estimated_minutes = EXCLUDED.estimated_minutes,
    sort_order = EXCLUDED.sort_order,
    version = EXCLUDED.version,
    updated_at = EXCLUDED.updated_at;"""
        )

    lines.append(
        f"""
DELETE FROM public.reading_questions
WHERE set_id IN ({id_list});"""
    )

    for s in sets:
        underline = s.get("underlineMap") or {}
        for q_index, q in enumerate(s["questions"]):
            highlight = underline.get(q["id"])
            highlight_sql = sql_str(highlight) if highlight else "NULL"
            lines.append(
                f"""
INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    '{q["id"]}',
    '{s["id"]}',
    {sql_str(q.get("type"))},
    {sql_str(q["stem"])},
    {q_index},
    '{q["correctOptionId"]}',
    {sql_str(q["explanation"])},
    {highlight_sql},
    {DEFAULT_REWARD}
);"""
            )
            for o_index, opt in enumerate(q["options"]):
                lines.append(
                    f"""
INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    '{q["id"]}',
    '{opt["id"]}',
    {sql_str(opt["text"])},
    {o_index}
);"""
                )

    return "\n".join(lines)


def main() -> None:
    if not READING_ROOT.exists():
        raise SystemExit(f"Missing reading assets at {READING_ROOT}")
    sets = load_sets()
    if not sets:
        raise SystemExit("No reading sets found")
    sql = build_ddl() + "\n" + build_seed(sets) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql, encoding="utf-8")
    q_count = sum(len(s["questions"]) for s in sets)
    o_count = sum(len(opt) for s in sets for q in s["questions"] for opt in [q["options"]])
    print(f"Wrote {OUT}")
    print(f"sets={len(sets)} questions={q_count} options={o_count}")


if __name__ == "__main__":
    main()
