-- Reading comprehension catalog (grade-8 starter bank)
-- Generated by scripts/generate_reading_seed.py — do not hand-edit seed rows.

CREATE TABLE IF NOT EXISTS public.reading_sets (
    set_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    title_zh TEXT,
    grade INT NOT NULL DEFAULT 8,
    difficulty TEXT NOT NULL DEFAULT 'medium',
    topic TEXT,
    passage TEXT NOT NULL,
    word_count INT NOT NULL DEFAULT 0,
    estimated_minutes INT NOT NULL DEFAULT 8,
    sort_order INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.reading_questions (
    question_id TEXT PRIMARY KEY,
    set_id TEXT NOT NULL REFERENCES public.reading_sets(set_id) ON DELETE CASCADE,
    question_type TEXT,
    stem TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    correct_option_id TEXT NOT NULL,
    explanation TEXT NOT NULL,
    highlight_word TEXT,
    reward_token INT NOT NULL DEFAULT 2
);

CREATE TABLE IF NOT EXISTS public.reading_options (
    question_id TEXT NOT NULL REFERENCES public.reading_questions(question_id) ON DELETE CASCADE,
    option_id TEXT NOT NULL,
    option_text TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (question_id, option_id)
);

CREATE INDEX IF NOT EXISTS reading_sets_sort_order_idx
    ON public.reading_sets (sort_order);

CREATE INDEX IF NOT EXISTS reading_questions_set_sort_idx
    ON public.reading_questions (set_id, sort_order);

ALTER TABLE public.reading_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_options ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view reading sets" ON public.reading_sets;
CREATE POLICY "Anyone can view reading sets"
    ON public.reading_sets FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view reading questions" ON public.reading_questions;
CREATE POLICY "Anyone can view reading questions"
    ON public.reading_questions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can view reading options" ON public.reading_options;
CREATE POLICY "Anyone can view reading options"
    ON public.reading_options FOR SELECT USING (true);

GRANT SELECT ON public.reading_sets TO anon, authenticated;
GRANT SELECT ON public.reading_questions TO anon, authenticated;
GRANT SELECT ON public.reading_options TO anon, authenticated;

-- Seed grade-8 reading bank

INSERT INTO public.reading_sets (
    set_id, title, title_zh, grade, difficulty, topic, passage,
    word_count, estimated_minutes, sort_order, version, updated_at
) VALUES (
    'r08-01',
    $seedie$Our School Garden Project$seedie$,
    $seedie$我们的校园花园项目$seedie$,
    8,
    $seedie$medium$seedie$,
    $seedie$school_life$seedie$,
    $seedie$Last spring, Class 8A started a small garden behind the school library. At first, the ground was hard and full of dry leaves. Nobody believed plants could grow there. Then Ms. Chen, our science teacher, brought tools, seeds, and a simple plan.

Every Tuesday afternoon, ten students worked in teams. One team cleaned the soil. Another team built wooden boxes for vegetables. A third team wrote labels with both English and Chinese names. We planted tomatoes, lettuce, and sunflowers. We also kept a garden diary. In the diary, we wrote the date, the weather, and what we did that day.

The work was not always easy. One week, heavy rain washed away some young plants. Another week, insects ate the lettuce leaves. Ms. Chen did not give us the answers at once. She asked, "What can we try next?" So we searched online, talked with the school gardener, and tried new ideas. We covered the soil with dry grass to keep water in. We also planted flowers that insects do not like near the lettuce.

By June, the garden looked green and lively. We <<harvested>> the first tomatoes and shared them with teachers. More importantly, we learned that science is not only in textbooks. It is also about careful observation, patience, and working together. Now other classes want to join the project next term.$seedie$,
    248,
    8,
    0,
    1,
    2026072901
)
ON CONFLICT (set_id) DO UPDATE SET
    title = EXCLUDED.title,
    title_zh = EXCLUDED.title_zh,
    grade = EXCLUDED.grade,
    difficulty = EXCLUDED.difficulty,
    topic = EXCLUDED.topic,
    passage = EXCLUDED.passage,
    word_count = EXCLUDED.word_count,
    estimated_minutes = EXCLUDED.estimated_minutes,
    sort_order = EXCLUDED.sort_order,
    version = EXCLUDED.version,
    updated_at = EXCLUDED.updated_at;

INSERT INTO public.reading_sets (
    set_id, title, title_zh, grade, difficulty, topic, passage,
    word_count, estimated_minutes, sort_order, version, updated_at
) VALUES (
    'r08-02',
    $seedie$Why Sleep Matters for Teenagers$seedie$,
    $seedie$为什么睡眠对青少年很重要$seedie$,
    8,
    $seedie$medium$seedie$,
    $seedie$health_science$seedie$,
    $seedie$Many teenagers say they feel tired at school. Some stay up late to finish homework. Others watch short videos until midnight. They may think, "I can sleep less now and rest more on weekends." But scientists say this idea is not helpful.

Sleep is not just "doing nothing." While we sleep, the brain sorts information from the day. It helps us remember what we learned. It also repairs the body and supports a healthy mood. For most teenagers, experts suggest about eight to ten hours of sleep each night. When sleep is too short, students may find it harder to focus in class. They may also get angry more easily or catch colds more often.

Why is it difficult for teenagers to sleep early? One reason is biological. During the teenage years, the body clock often shifts later. That means many teens do not feel sleepy until later in the evening. Another reason is lifestyle. Bright screens before bed can <<trick>> the brain into thinking it is still daytime. Heavy homework and worry can also keep the mind busy.

What can students do? First, keep a regular bedtime, even on weekends when possible. Second, put phones away at least thirty minutes before sleep. Third, do quiet activities such as reading a paper book or listening to soft music. Finally, if stress about tests is too strong, talk with parents or teachers. Better sleep will not solve every problem, but it can make busy school days easier to manage.$seedie$,
    256,
    8,
    1,
    1,
    2026072901
)
ON CONFLICT (set_id) DO UPDATE SET
    title = EXCLUDED.title,
    title_zh = EXCLUDED.title_zh,
    grade = EXCLUDED.grade,
    difficulty = EXCLUDED.difficulty,
    topic = EXCLUDED.topic,
    passage = EXCLUDED.passage,
    word_count = EXCLUDED.word_count,
    estimated_minutes = EXCLUDED.estimated_minutes,
    sort_order = EXCLUDED.sort_order,
    version = EXCLUDED.version,
    updated_at = EXCLUDED.updated_at;

INSERT INTO public.reading_sets (
    set_id, title, title_zh, grade, difficulty, topic, passage,
    word_count, estimated_minutes, sort_order, version, updated_at
) VALUES (
    'r08-03',
    $seedie$The Wallet on the Bus$seedie$,
    $seedie$公交车上的钱包$seedie$,
    8,
    $seedie$easy$seedie$,
    $seedie$values_narrative$seedie$,
    $seedie$On a rainy Monday morning, Lin Hao took Bus 12 to school as usual. The bus was crowded. He held his backpack close and looked out of the wet window. When the bus stopped near the park, an old man stood up and hurried to the door. A moment later, Lin Hao noticed a brown wallet on the empty seat.

Lin Hao picked it up. Inside there was a student ID card, some money, and a small photo of a girl with her grandparents. The name on the card was Zhang Yue. Lin Hao felt nervous. If he did nothing, the owner might lose important things. If he shouted on the busy bus, people might not hear him clearly.

He decided to give the wallet to the bus driver. The driver smiled and said, "Thank you. I will keep it safe and call the school number on the card." After school, Lin Hao's teacher told the class that Zhang Yue from Class 8C had got her wallet back. She had almost cried when she found it missing, because the photo was the only one of her late grandmother.

The next day, Zhang Yue found Lin Hao at the school gate. She did not say many words. She just handed him a handmade thank-you card. Lin Hao felt a little shy, but also proud. He understood that honesty is not always <<dramatic>>. Sometimes it is a quiet choice on an ordinary morning.$seedie$,
    238,
    7,
    2,
    1,
    2026072901
)
ON CONFLICT (set_id) DO UPDATE SET
    title = EXCLUDED.title,
    title_zh = EXCLUDED.title_zh,
    grade = EXCLUDED.grade,
    difficulty = EXCLUDED.difficulty,
    topic = EXCLUDED.topic,
    passage = EXCLUDED.passage,
    word_count = EXCLUDED.word_count,
    estimated_minutes = EXCLUDED.estimated_minutes,
    sort_order = EXCLUDED.sort_order,
    version = EXCLUDED.version,
    updated_at = EXCLUDED.updated_at;

INSERT INTO public.reading_sets (
    set_id, title, title_zh, grade, difficulty, topic, passage,
    word_count, estimated_minutes, sort_order, version, updated_at
) VALUES (
    'r08-04',
    $seedie$Shared Bikes in Our City$seedie$,
    $seedie$我们城市里的共享单车$seedie$,
    8,
    $seedie$medium$seedie$,
    $seedie$public_life$seedie$,
    $seedie$Shared bikes have become a common part of city life. With a smartphone, people can unlock a bike, ride to the subway station or school, and leave it in a parking area. For many students, shared bikes save time on short trips. They are also cheaper than taxis for everyday travel.

However, shared bikes also bring problems. Some riders leave bikes in the middle of sidewalks. Then parents with strollers and older people with walking sticks find it hard to pass. A few people damage QR codes or throw bikes into rivers. These actions make the service worse for everyone and create extra work for city workers.

To improve the situation, our city made clearer rules last year. Riders must park inside white lines near bus stops and schools. If a bike is left in a wrong place too often by the same account, the app may add a small fine. Companies also hire workers to move bikes at busy hours. Some schools now teach "bike manners" in moral education class. Students learn that public tools need public care.

Shared bikes are not just machines. They are a test of how we share space in a busy city. When we park carefully, we protect other people's safety. When we report broken bikes in the app, we help the next rider. Technology can make travel easier, but good habits make the city kinder. Next time you finish a ride, take ten more seconds to park well. That small action matters.$seedie$,
    262,
    8,
    3,
    1,
    2026072901
)
ON CONFLICT (set_id) DO UPDATE SET
    title = EXCLUDED.title,
    title_zh = EXCLUDED.title_zh,
    grade = EXCLUDED.grade,
    difficulty = EXCLUDED.difficulty,
    topic = EXCLUDED.topic,
    passage = EXCLUDED.passage,
    word_count = EXCLUDED.word_count,
    estimated_minutes = EXCLUDED.estimated_minutes,
    sort_order = EXCLUDED.sort_order,
    version = EXCLUDED.version,
    updated_at = EXCLUDED.updated_at;

INSERT INTO public.reading_sets (
    set_id, title, title_zh, grade, difficulty, topic, passage,
    word_count, estimated_minutes, sort_order, version, updated_at
) VALUES (
    'r08-05',
    $seedie$A Morning at the Science Museum$seedie$,
    $seedie$科学博物馆的一上午$seedie$,
    8,
    $seedie$medium$seedie$,
    $seedie$stem_visit$seedie$,
    $seedie$Last Saturday, our class visited the city science museum. Many students expected only quiet halls and glass boxes. Instead, the museum felt alive. In the first hall, we tried a <<hands-on>> weather station. By turning a handle, we could make wind stronger and watch how paper clouds moved. A guide explained that scientists use real tools to measure wind speed and rainfall.

Next, we entered the energy room. There, a bicycle was connected to a small light. When a classmate pedaled faster, the light became brighter. When she slowed down, the light almost went out. We laughed, but we also understood a serious idea: energy does not appear from nowhere. If we want light, heat, or motion, something must provide power.

The most surprising part was the robotics corner. Two student volunteers from a high school showed a robot that could pick up plastic bottles and drop them into a recycling box. The robot was slow and sometimes missed the bottle. Still, the volunteers said failure was part of building. They changed the program twice while we watched.

Before we left, each group chose one exhibit and wrote three questions about it. My group asked how the robot "sees" objects, who repairs museum machines, and whether teenagers can join weekend workshops. The guide gave us a leaflet with club information. On the bus back to school, the noise was different. Students were not only talking about funny moments. They were also arguing about ideas. That morning did not make us scientists at once, but it made science feel close enough to touch.$seedie$,
    268,
    8,
    4,
    1,
    2026072901
)
ON CONFLICT (set_id) DO UPDATE SET
    title = EXCLUDED.title,
    title_zh = EXCLUDED.title_zh,
    grade = EXCLUDED.grade,
    difficulty = EXCLUDED.difficulty,
    topic = EXCLUDED.topic,
    passage = EXCLUDED.passage,
    word_count = EXCLUDED.word_count,
    estimated_minutes = EXCLUDED.estimated_minutes,
    sort_order = EXCLUDED.sort_order,
    version = EXCLUDED.version,
    updated_at = EXCLUDED.updated_at;

DELETE FROM public.reading_questions
WHERE set_id IN ('r08-01', 'r08-02', 'r08-03', 'r08-04', 'r08-05');

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-01-q1',
    'r08-01',
    $seedie$main_idea$seedie$,
    $seedie$What is the passage mainly about?$seedie$,
    0,
    'A',
    $seedie$全文围绕 8A 班开辟校园花园、遇到困难并解决、以及从中学到的道理展开，故主旨是 A。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q1',
    'A',
    $seedie$How Class 8A built a school garden and what they learned$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q1',
    'B',
    $seedie$Why Ms. Chen stopped teaching science$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q1',
    'C',
    $seedie$How to cook tomatoes from a school garden$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q1',
    'D',
    $seedie$Why the school library needed more books$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-01-q2',
    'r08-01',
    $seedie$detail$seedie$,
    $seedie$What did the third team do?$seedie$,
    1,
    'C',
    $seedie$第二段明确写到第三组负责写中英双语标签。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q2',
    'A',
    $seedie$They cleaned the soil.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q2',
    'B',
    $seedie$They built wooden boxes.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q2',
    'C',
    $seedie$They wrote labels in English and Chinese.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q2',
    'D',
    $seedie$They cooked food for teachers.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-01-q3',
    'r08-01',
    $seedie$detail$seedie$,
    $seedie$How did the students solve the insect problem?$seedie$,
    2,
    'C',
    $seedie$第三段末尾提到在生菜旁种植虫子不喜欢的花，作为应对虫害的办法之一。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q3',
    'A',
    $seedie$They stopped planting lettuce.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q3',
    'B',
    $seedie$They asked Ms. Chen to do all the work.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q3',
    'C',
    $seedie$They planted flowers that insects do not like near the lettuce.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q3',
    'D',
    $seedie$They moved the garden into the library.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-01-q4',
    'r08-01',
    $seedie$inference$seedie$,
    $seedie$What can we infer about Ms. Chen?$seedie$,
    3,
    'A',
    $seedie$她没有立刻给答案，而是问“下一步可以试什么”，引导学生自己查找、讨论和尝试，说明她重视自主探究。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q4',
    'A',
    $seedie$She wanted students to think and solve problems by themselves.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q4',
    'B',
    $seedie$She thought gardening was a waste of time.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q4',
    'C',
    $seedie$She never helped the students at all.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q4',
    'D',
    $seedie$She only cared about beautiful flowers.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-01-q5',
    'r08-01',
    $seedie$vocabulary$seedie$,
    $seedie$The word "harvested" in the last paragraph is closest in meaning to ______.$seedie$,
    4,
    'B',
    $seedie$结合后文 "shared them with teachers"，harvested 指把成熟的番茄采摘/收获下来。$seedie$,
    $seedie$harvested$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q5',
    'A',
    $seedie$bought$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q5',
    'B',
    $seedie$collected from the plants$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q5',
    'C',
    $seedie$threw away$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-01-q5',
    'D',
    $seedie$drew pictures of$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-02-q1',
    'r08-02',
    $seedie$main_idea$seedie$,
    $seedie$The passage is mainly written to ______.$seedie$,
    0,
    'A',
    $seedie$文章先说明睡眠作用与睡眠不足的影响，再分析原因并给出建议，写作目的是 A。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q1',
    'A',
    $seedie$explain why sleep is important for teenagers and how to sleep better$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q1',
    'B',
    $seedie$tell teenagers to stop doing all homework$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q1',
    'C',
    $seedie$prove that weekends are unnecessary$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q1',
    'D',
    $seedie$advertise a new kind of phone$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-02-q2',
    'r08-02',
    $seedie$detail$seedie$,
    $seedie$According to the passage, how much sleep do most teenagers need each night?$seedie$,
    1,
    'C',
    $seedie$第二段写明专家建议青少年每晚大约睡 8 到 10 小时。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q2',
    'A',
    $seedie$Four to five hours$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q2',
    'B',
    $seedie$Five to six hours$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q2',
    'C',
    $seedie$Eight to ten hours$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q2',
    'D',
    $seedie$Twelve to fourteen hours$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-02-q3',
    'r08-02',
    $seedie$detail$seedie$,
    $seedie$Which of the following is mentioned as a biological reason for late sleep?$seedie$,
    2,
    'A',
    $seedie$第三段指出青少年时期生物钟常常后移，这是生理性原因。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q3',
    'A',
    $seedie$Teenagers' body clocks often shift later.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q3',
    'B',
    $seedie$Schools start too early for teachers.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q3',
    'C',
    $seedie$Parents always turn off the lights at 8 p.m.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q3',
    'D',
    $seedie$Short videos make homework shorter.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-02-q4',
    'r08-02',
    $seedie$inference$seedie$,
    $seedie$What does the writer think about "sleeping less on weekdays and resting more on weekends"?$seedie$,
    3,
    'B',
    $seedie$首段引用这种想法后，用 "scientists say this idea is not helpful" 直接否定。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q4',
    'A',
    $seedie$It is the best plan for busy students.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q4',
    'B',
    $seedie$It is not a helpful idea.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q4',
    'C',
    $seedie$It is required by all scientists.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q4',
    'D',
    $seedie$It only works for adults.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-02-q5',
    'r08-02',
    $seedie$vocabulary$seedie$,
    $seedie$In Paragraph 3, the word "trick" most nearly means ______.$seedie$,
    4,
    'A',
    $seedie$亮屏会让大脑误以为仍是白天，此处 trick 表示“欺骗/误导”。$seedie$,
    $seedie$trick$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q5',
    'A',
    $seedie$make someone believe something false$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q5',
    'B',
    $seedie$help someone finish homework$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q5',
    'C',
    $seedie$teach someone a new language$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-02-q5',
    'D',
    $seedie$invite someone to a party$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-03-q1',
    'r08-03',
    $seedie$main_idea$seedie$,
    $seedie$What is the best title for the passage?$seedie$,
    0,
    'B',
    $seedie$故事核心是林浩在平常早上选择把钱包交给司机归还失主，结尾点明“诚实有时是安静的选择”，故 B 最贴切。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q1',
    'A',
    $seedie$A Crowded Bus Every Day$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q1',
    'B',
    $seedie$A Quiet Choice to Return a Wallet$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q1',
    'C',
    $seedie$How to Make a Thank-You Card$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q1',
    'D',
    $seedie$Zhang Yue's Photo Collection$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-03-q2',
    'r08-03',
    $seedie$detail$seedie$,
    $seedie$Where did Lin Hao find the wallet?$seedie$,
    1,
    'B',
    $seedie$第一段写老人下车后，林浩在空座位上发现棕色钱包。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q2',
    'A',
    $seedie$In the school library$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q2',
    'B',
    $seedie$On an empty seat of the bus$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q2',
    'C',
    $seedie$At the school gate$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q2',
    'D',
    $seedie$Inside his own backpack$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-03-q3',
    'r08-03',
    $seedie$detail$seedie$,
    $seedie$Why was the photo especially important to Zhang Yue?$seedie$,
    2,
    'B',
    $seedie$第三段老师转述：那是她已故奶奶的唯一一张照片。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q3',
    'A',
    $seedie$It was a picture of her favorite teacher.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q3',
    'B',
    $seedie$It was the only photo of her late grandmother.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q3',
    'C',
    $seedie$It showed her prize from a writing contest.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q3',
    'D',
    $seedie$It was needed for a bus ticket.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-03-q4',
    'r08-03',
    $seedie$inference$seedie$,
    $seedie$Why did Lin Hao give the wallet to the driver instead of keeping it himself?$seedie$,
    3,
    'A',
    $seedie$他担心喊话无效，于是交给司机保管并联系卡片上的学校电话，目的是安全归还。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q4',
    'A',
    $seedie$He wanted the driver to help return it safely.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q4',
    'B',
    $seedie$He did not like the photo inside.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q4',
    'C',
    $seedie$He hoped to get money from the driver.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q4',
    'D',
    $seedie$He was afraid of Zhang Yue.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-03-q5',
    'r08-03',
    $seedie$vocabulary$seedie$,
    $seedie$The word "dramatic" in the last paragraph is closest in meaning to ______.$seedie$,
    4,
    'A',
    $seedie$与后文 quiet choice 相对，dramatic 指轰轰烈烈、充满戏剧性的表现。$seedie$,
    $seedie$dramatic$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q5',
    'A',
    $seedie$full of strong excitement or big scenes$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q5',
    'B',
    $seedie$very cheap$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q5',
    'C',
    $seedie$related to math homework$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-03-q5',
    'D',
    $seedie$completely silent forever$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-04-q1',
    'r08-04',
    $seedie$main_idea$seedie$,
    $seedie$What is the writer's main point?$seedie$,
    0,
    'A',
    $seedie$文章肯定共享单车便利，同时指出乱停等问题，并介绍规则与文明骑行，主旨是 A。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q1',
    'A',
    $seedie$Shared bikes are useful, but riders need good manners and clear rules.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q1',
    'B',
    $seedie$Cities should ban all shared bikes at once.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q1',
    'C',
    $seedie$Students should never use smartphones.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q1',
    'D',
    $seedie$Taxis are always better than bikes.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-04-q2',
    'r08-04',
    $seedie$detail$seedie$,
    $seedie$According to the city rules, where should riders park shared bikes?$seedie$,
    1,
    'B',
    $seedie$第三段写明须停在公交站和学校附近的白色标线内。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q2',
    'A',
    $seedie$In the middle of sidewalks$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q2',
    'B',
    $seedie$Inside white lines near bus stops and schools$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q2',
    'C',
    $seedie$Inside classroom buildings$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q2',
    'D',
    $seedie$Anywhere beside a river$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-04-q3',
    'r08-04',
    $seedie$detail$seedie$,
    $seedie$What may happen if the same account leaves bikes in wrong places too often?$seedie$,
    2,
    'A',
    $seedie$第三段提到同一账号频繁乱停，应用可能加收小额罚款。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q3',
    'A',
    $seedie$The rider may get a small fine in the app.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q3',
    'B',
    $seedie$The rider will receive free movie tickets.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q3',
    'C',
    $seedie$The city will close all schools.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q3',
    'D',
    $seedie$The bike will fly back by itself.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-04-q4',
    'r08-04',
    $seedie$inference$seedie$,
    $seedie$Why does the writer say shared bikes are "a test"?$seedie$,
    3,
    'A',
    $seedie$末段把共享单车比作对“如何共享城市空间”的考验，强调责任与习惯。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q4',
    'A',
    $seedie$Because they check whether people can share public space responsibly.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q4',
    'B',
    $seedie$Because every rider must take an English exam.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q4',
    'C',
    $seedie$Because bikes are used only in science museums.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q4',
    'D',
    $seedie$Because companies want to sell more phones.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-04-q5',
    'r08-04',
    $seedie$writer_attitude$seedie$,
    $seedie$Which word best describes the writer's attitude toward shared bikes?$seedie$,
    4,
    'B',
    $seedie$作者既肯定便利，也正视问题并给出可行建议，态度理性务实。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q5',
    'A',
    $seedie$Completely negative$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q5',
    'B',
    $seedie$Balanced and practical$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q5',
    'C',
    $seedie$Angry and hopeless$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-04-q5',
    'D',
    $seedie$Uninterested$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-05-q1',
    'r08-05',
    $seedie$main_idea$seedie$,
    $seedie$What did the class learn from the museum visit?$seedie$,
    0,
    'A',
    $seedie$全文写互动展项、能源体验、机器人展示及学生提问，结尾强调科学变得可触摸，主旨是 A。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q1',
    'A',
    $seedie$Science can be experienced through real activities, not only read in books.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q1',
    'B',
    $seedie$Museums should remove all robots.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q1',
    'C',
    $seedie$Students should never ask questions.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q1',
    'D',
    $seedie$Weather can be controlled by paper clouds alone.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-05-q2',
    'r08-05',
    $seedie$detail$seedie$,
    $seedie$What happened in the energy room when a classmate pedaled faster?$seedie$,
    1,
    'A',
    $seedie$第二段：踩得越快，灯越亮。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q2',
    'A',
    $seedie$The light became brighter.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q2',
    'B',
    $seedie$The robot picked up more bottles.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q2',
    'C',
    $seedie$The paper clouds stopped moving.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q2',
    'D',
    $seedie$The museum closed early.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-05-q3',
    'r08-05',
    $seedie$detail$seedie$,
    $seedie$What task could the robot do?$seedie$,
    2,
    'B',
    $seedie$第三段写机器人捡起塑料瓶并放入回收箱。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q3',
    'A',
    $seedie$Cook lunch for visitors$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q3',
    'B',
    $seedie$Pick up plastic bottles and put them into a recycling box$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q3',
    'C',
    $seedie$Drive the school bus home$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q3',
    'D',
    $seedie$Measure rainfall outside the museum$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-05-q4',
    'r08-05',
    $seedie$inference$seedie$,
    $seedie$Why did the volunteers change the program twice?$seedie$,
    3,
    'A',
    $seedie$志愿者说失败是搭建过程的一部分，并当着学生的面改了两次程序，说明在排错改进。$seedie$,
    NULL,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q4',
    'A',
    $seedie$Because building robots includes fixing problems after failure.$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q4',
    'B',
    $seedie$Because the museum asked them to stop showing the robot.$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q4',
    'C',
    $seedie$Because they wanted to make the light brighter.$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q4',
    'D',
    $seedie$Because the class had no questions.$seedie$,
    3
);

INSERT INTO public.reading_questions (
    question_id, set_id, question_type, stem, sort_order,
    correct_option_id, explanation, highlight_word, reward_token
) VALUES (
    'r08-05-q5',
    'r08-05',
    $seedie$vocabulary$seedie$,
    $seedie$The phrase "hands-on" in Paragraph 1 suggests that visitors can ______.$seedie$,
    4,
    'B',
    $seedie$后文写转动把手制造风力，说明 hands-on 指亲自动手体验。$seedie$,
    $seedie$hands-on$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q5',
    'A',
    $seedie$only look from far away$seedie$,
    0
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q5',
    'B',
    $seedie$touch and try the activity themselves$seedie$,
    1
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q5',
    'C',
    $seedie$buy the weather station$seedie$,
    2
);

INSERT INTO public.reading_options (
    question_id, option_id, option_text, sort_order
) VALUES (
    'r08-05-q5',
    'D',
    $seedie$sleep in the hall$seedie$,
    3
);
